/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StudentsStudentIdIndexImport } from './routes/students/$studentId/index'
import { Route as StudentsStudentIdCartImport } from './routes/students/$studentId/cart'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsStudentIdIndexRoute = StudentsStudentIdIndexImport.update({
  path: '/students/$studentId/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsStudentIdCartRoute = StudentsStudentIdCartImport.update({
  path: '/students/$studentId/cart',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/students/$studentId/cart': {
      id: '/students/$studentId/cart'
      path: '/students/$studentId/cart'
      fullPath: '/students/$studentId/cart'
      preLoaderRoute: typeof StudentsStudentIdCartImport
      parentRoute: typeof rootRoute
    }
    '/students/$studentId/': {
      id: '/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students/$studentId/cart': typeof StudentsStudentIdCartRoute
  '/students/$studentId': typeof StudentsStudentIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students/$studentId/cart': typeof StudentsStudentIdCartRoute
  '/students/$studentId': typeof StudentsStudentIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students/$studentId/cart': typeof StudentsStudentIdCartRoute
  '/students/$studentId/': typeof StudentsStudentIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/students/$studentId/cart'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/students/$studentId/cart' | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/students/$studentId/cart'
    | '/students/$studentId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StudentsStudentIdCartRoute: typeof StudentsStudentIdCartRoute
  StudentsStudentIdIndexRoute: typeof StudentsStudentIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StudentsStudentIdCartRoute: StudentsStudentIdCartRoute,
  StudentsStudentIdIndexRoute: StudentsStudentIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/students/$studentId/cart",
        "/students/$studentId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/students/$studentId/cart": {
      "filePath": "students/$studentId/cart.tsx"
    },
    "/students/$studentId/": {
      "filePath": "students/$studentId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
